# Generated by Django 2.1.5 on 2019-02-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_msg', '0002_message_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='status',
            new_name='success',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(verbose_name='Send date'),
        ),
    ]
