# Generated by Django 2.1.5 on 2019-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_msg', '0005_auto_20190207_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Send date'),
        ),
    ]
